# get all snaps
curl -X GET http://localhost:8080/snaps

# get snap by 

### invalid uuid
curl -X GET http://localhost:8080/snaps/e0462215-9238-4919-a4e0-0be725d7ea7

### existent uuid
curl -X GET http://localhost:8080/snaps/e0462215-9238-4919-a4e0-0be725d7ed57
### uuid not found

curl -X GET http://localhost:8080/snaps/e0462215-9238-4919-a4e0-0be725d7ea7e

# create snap

### message ok
curl -X POST http://localhost:8080/snaps \
     -H "Content-Type: application/json" \
     -d '{
           "message": "Hello, World!"
         }'