name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install docker docker-compose -y
    - name: Build the Docker image
      run: npm run ci-test
